name: Spectator
version: 1.1
author: kosakriszi
main: com.kosakorner.spectator.Spectator
softdepend: [ProtocolLib]

commands:
  spectate:
    aliases: [spec]
    description: Access to spectate.
    permission: spectator.use
  spectatereload:
    aliases: [specreload]
    description: Reload the plugin's configs.
    permission: spectator.reload

permissions:
  spectator.use.*:
    description: Access to all Spectator commands.
    children:
      spectator.use.teleport: true
      spectator.use.inventory: true
  spectator.bypass.*:
    description: Bypass certain Spectator features.
    children:
      spectator.bypass.tablist: true
  spectator.reload:
    description: Access to reload all Spectator configs.